FROM node:16 as builder

COPY package.json  ./

RUN npm install 

RUN mkdir /ng-app

RUN mv ./node_modules ./ng-app

WORKDIR /ng-app

COPY . .

RUN npm run ng build --prod

FROM nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /ng-app/dist/animal-shelter-mainfe /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]