version: "3.2"
services:
  client:
    build: ./microservice-client
    ports:
      - 3000:3000
    environment:
      RABBITMQ_HOST: rabbitmq
  microservices:
    build: ./microservices-app
    environment:
      RABBITMQ_HOST: rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq

