version: "3.2"
services:
  animal-shelter-client:
    build: ./backend/animal-shelter-client
    ports:
      - 3000:3000
    environment:
      RABBITMQ_HOST: rabbitmq
  animal-shelter-authentication:
    build: ./backend/animal-shelter-authentication
    environment:
      RABBITMQ_HOST: rabbitmq
  animal-shelter-animals:
    build: ./backend/animal-shelter-animals
    environment:
      RABBITMQ_HOST: rabbitmq
  # animal-shelter-media:
  #   build: ./backend/animal-shelter-media
  #   environment:
  #     RABBITMQ_HOST: rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
  # animal-shelter-mainfe:
  #   build: ./frontend/animal-shelter-mainfe
  # animal-shelter-authenticationfe:
  #   build: ./frontend/animal-shelter-authentication
  # animal-shelter-home:
  #   build: ./frontend/animal-shelter-home  
