FROM node:16 as builder

COPY package.json  ./

RUN npm install 

RUN mkdir /mfe1-app

RUN mv ./node_modules ./mfe1-app

WORKDIR /mfe1-app

COPY . .

RUN npm run ng build --prod

FROM nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /mfe-app1/dist/animal-shelter-home /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]